language: python
python:
- '3.5'
script:
- echo 'TODO'
deploy:
  provider: pypi
  user: renwei2
  password:
    secure: McYQWNyfv4o0llWLzxM6DlNjw8OYeLSHfoKrcvWTd2T79MUtCC8520oOc6OZXrw1vSjJtcQKJm9hWk93PnG2CKE/aXs3ocSMFc8UMN/6hqsyUV6O7Wdip9FGTj9+nUhDz6rTMdLwmpCfzPqy+lao5ksAcX80f3vqh7rLuAvgatVvtqfjmmQKwvPve0mj7xgvQLp2uH3DjBSG6IhVZvCJ/3OiX+eM88rba+aSHFaxqgeXFF6IdQDKkEoaCwr5U/IEDuXa0+94FGSxj81R+l+KGAGay7B1kgP//34fp4XFtB88I0zaz/xsJAtE0n8izN0R8Y3ic2U1UL3LXdW2jxciG1S2wnRUgSeZJIxPZXnB2FKayWfkHmiOrmUuQ+CPBXB2HBKiPAGduQrBZDMYL2vcAlK9Xm860fmczZA83pEuNnX7Tl1lQUC4q/KGPdgkbAGqeCAsbVsPDKs+nxGfsztX6WXaaHw++jxW9lSZNVdqqACjQVYVLuRxmIrLLlYWQJZhtg5XaHqy9RM3l9BCk6llD8nMFxitTgbpWeUztPW+5Oj7e/gaPS3UQJshAkeM9UYQg8O72ypCZlAyMAhOjshtlgLjep7TxwFxCPrsb8F4FWTtzZw4e7xlBwV1GEd0jPCS3XI8UX8HtOGn5yOJdd4SPiVH8gfBnsxb4l2XdtrLQ7Y=
  on:
    tags: true
  distributions: sdist bdist_wheel
